### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypeR#13]
See [hypepy](https://github.com/UBC-MDS/hypepy) for additional feedback.

- None of the functions in hyp_test_testing.R will work either because 'data' isn't defined. See for example: https://www.johndcook.com/blog/2013/06/12/example-of-unit-testing-r-code-with-testthat/ 
- 'data' also isn't defined in:
  - `# Check that output is an array
test_that("output data type?", {
  expect_true(is.array(conf_int(data)))
})`
- The rest of the tests look good.

**Comment by joesdesk** [comment]
Resolved in pull request #14
