### ISSUE TITLE
Change some wording in your docs

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/hypeR#25]
For `conf_int()` the docs say that this "Computes the confidence interval of the mean from a population".  That is not really correct since we can never measure a true population. What you are really doing is computing the confidence interval of the mean from a sample (of the population). Please change "population"  to "sample" in this case. Also ensure this error is propagated elsewhere in your docs.

**Comment by siobhanmccarter** [comment]
Fixed.
