### ISSUE TITLE
Function documentation is incomplete and not formatted correctly

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/hypeR#26]
When I install your package and try to use the help to read your function documentation I get errors:
```
> library(hypeR)
> ?conf_int
No documentation for ‘conf_int’ in specified packages and libraries:
you could try ‘??conf_int’
> ?hyp_test
No documentation for ‘hyp_test’ in specified packages and libraries:
you could try ‘??hyp_test’
> ?t_test
No documentation for ‘t_test’ in specified packages and libraries:
you could try ‘??t_test’
```

I think this is because you do not use ROxygen formatted documentation with your functions in the `.R` file. See how to fix this in [the object documentation chapter](http://r-pkgs.had.co.nz/man.html) from R packages by Hadley Wickham.

**Comment by idespot** [comment]
The functions have been formatted on the `.R` file using roxygen2.
