### ISSUE TITLE
Concerned about the usefullness of your statistical tests

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/hypeR#27]
With hypothesis testing, usually people have at least 2 samples they want to compare and assess whether they come from same or different populations. Your statistical tests however only take one sample but compare to some mean that a user would have to measure/calculate from some other sample. Would it not be more useful for your function to take in 2 samples (as 2 vectors, or a dataframe, or two columns of a dataframe, or a tidy dataframe with a label column) and perform the tests on these? 

Perhaps your design is really useful, but your documentation (README and Vignette) do not clearly explain this. Please either change the functions as I suggest above or provide more motivating examples and explanations.

**Comment by joesdesk** [comment]
Addressed by @siobhanmccarter in #39
