### ISSUE TITLE
Something preventing `devtools::spell_check()` from working

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/hypeR#31]
Something is preventing `devtools::spell_check()` from working... I have never seen this before... Maybe if you address some of the other problems this will go away? Please check. If not, we can work together to solve this (and then find out if you have any spelling errors :wink:).

```
>devtools::spell_check()
Error in sprintf(fmt, "  WORD") : 
  invalid format '%--Inf'; use format %s for character objects
In addition: Warning message:
In max(nchar(words)) : no non-missing arguments to max; returning -Inf
```

**Comment by joesdesk** [comment]
A problem seen by at least one other person; posted as an issue https://github.com/r-lib/devtools/pull/1430. Still seen after all other warnings errors and notes removed, which can be seen from the Travis CI output: https://travis-ci.org/UBC-MDS/hypeR.
