### ISSUE TITLE
Z-test/T-Test 

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypeR#5]
- The z_score requires the user knows the population standard deviation. You should also handle the much more common case where population sd is unknown (i.e use a t-test).

**Comment by vmasrani** [comment]
Moving each bullet to its own issue to track progress.

**Comment by idespot** [comment]
The function will be revised as a t-test rather than computing a z_score.

**Comment by joesdesk** [comment]
See 716954b9fb0807d01d4833315
