### ISSUE TITLE
Project goal - wrapper or reimplementation? 

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypeR#7]
- Is the goal to reimplement to existing scipy functions or to extend scipy's functionality? Either is fine but be clear about your objectives. 
- Whatever your decision(s) make sure sensible errors are returned in the case when a user enters invalid data. Also consider handling as many data types as possible so your package can easily interface with existing code.

**Comment by joesdesk** [comment]
See 716954b9fb0807d01d4833315...
