### ISSUE TITLE
Function input handling

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypeR#8]
- What kind of input will your functions handle? 
  - 1d or multivariate data? Missing values?
  - Continuous or discrete? 
  - Lists, tuples, numpy arrays, panda dataframes, output from scikit-learn?

**Comment by siobhanmccarter** [comment]
Our functions will handle:

- 1D data. Missing values will be disregarded.

- Both continuous and discrete data can be used.

- It takes in lists and numpy arrays.

**Comment by joesdesk** [comment]
See 716954b9fb0807d01d4833315
